samples: samples_complete.tsv

#first letter(s)
#l = low
#m = mid
#h = high
#vh = very high
#second/third letter
#m = memory
#t = time
#c = cores
lm: 500
mm: 8000
hm: 50000
vhm: 90000
lt: 10
mt: 300
ht: 3000
vht: 10000
lc: 8
mc: 16
hc: 32

# input - output
output: /group/dominguez/shared_notebooks/Immune_variation/mapping
input: /project/immune_variation/raw_data/transfer-from-GF/RITM0027809

reference:
  chm13: /project/immune_variation/supporting_files/reference/chm13v2/chm13v2.0_maskedY_rCRS.fa.gz
  grch38: /project/immune_variation/supporting_files/reference/grch38/GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions_v2.fasta.gz

reference_uncompressed:
  grch38: /project/immune_variation/supporting_files/reference/grch38/GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions_v2.fasta

chain_file: /group/dominguez/shared_notebooks/Immune_variation/mapping/NP057/hs1ToHg38.over.chain